baseURL = "https://peterfaria.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Peter Faria"
title = "Peter Faria."
theme = "vitae"
enableRobotsTXT = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
keywords = ["Peter","Faria", "Peter Faria", "blog", "rss"]
description = "Hi. I'm Peter. This is my blog."
title = "It's me, Peter Faria."
subtitle = "All about me."

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/zshift"

[[params.social]]
name = "Mastadon"
icon = "fab fa-mastadon"
url = "https://hachyderm.io/@zshift"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
